---
swagger: "2.0"
info:
  description: "Aucune description"
  version: "1.0.0"
  title: "testB"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /r:
    get:
      summary: "getSiren"
      parameters:
      - name: "siren"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: "Status 200"
      security:
      - {}
